services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3000:3000
    networks:
      - common-networks

  mysql-container:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sens
      MYSQL_DATABASE: login_test
    networks:
      - common-networks
    volumes:
      - /root/mysql-volumes:/var/lib/mysql
  redis-container:
    image: redis
    networks:
      - common-networks
    volumes:
      - /root/redis-volumes/redis:/data

networks:
  common-networks:
    driver: bridge